### ISSUE TITLE
How to handle links between DNAs?

### ISSUE THREAD

**Issue by pospi** [holo-rea/holo-rea#11]
I'm running into a decision point where [one side of a network fires a `call` into another network](https://github.com/holo-rea/holo-rea/blob/6e65145/happs/observation/zomes/main/code/src/fulfillment_requests.rs#L61), and the other side [only deals with its own internal links](https://github.com/holo-rea/holo-rea/blob/6e65145/happs/planning/zomes/main/code/src/fulfillment_requests.rs#L46).

I'm now wondering under which conditions links between networks need to be updated in both directions- usually it is a "foreign key" type relationship, where one side of the relationship controls the other. So in this case, I can't update `Commitment.fulfilledBy` to change the associated `EconomicEvent`s, I have to change each `EconomicEvent.fulfilled` for any given commitment.

What's the best way to make this bi-directional? Will any of these kinds of linking operations all *need* to be updated in both directions, or will there always be sender/receiver roles in play? (in this case, *'sender'* = `EconomicEvent` & *'receiver'* = the `Commitment`s which an `EconomicEvent` `fulfills`).

**Comment by fosterlynn** [comment]
>So in this case, I can't update Commitment.fulfilledBy to change the associated EconomicEvents, I have to change each EconomicEvent.fulfilled for any given commitment.

>Will any of these kinds of linking operations all need to be updated in both directions, or will there always be sender/receiver roles in play?

I don't know the general answer to that question, but we could do an exercise and look at everything if it is useful.  In this particular example, it will always be triggered by the EconomicEvent side, since that is the only way to fulfill a Commitment

**Comment by pospi** [comment]
Thinking on it more, it might actually not matter if we decompose operations into more fundamental pieces. Will close this for now and reopen if it becomes a problem.
