### ISSUE TITLE
Implement registration of agents joining a network

### ISSUE THREAD

**Issue by pospi** [holo-rea/holo-rea#146]
- [x] Add a configurable set of allowed agent IDs in `app.json` for the Agent DNA, to allow for private groups
- [x] Write agent ID publicly to the DHT on joining
- Standard pluggable APIs to:
    - [x] retrieve all registered agents in the DNA
    - [x] hash-based existence agent registration check (i.e. fully-private DHT where participants are not known outside the network)
- [x] Implement `agent(id)` and `allAgents` GraphQL queries
- [x] Implement links between existing DNAs & agents:
    - [x] observation
    - [x] planning
    - [x] proposal
        - [x] tests in `test_proposedto_crud.js`

See https://forum.holochain.org/t/agent-registry-dna/2394/ for more.

**Comment by pospi** [comment]
Started this in a new project https://github.com/holochain-open-dev/agent-registration

When it gets to REA-specific functionality, will link the newly developed core modules into this project's build system. There are [still a few publish workflow things](https://forum.holochain.org/t/agent-registry-dna/2394/10?u=pospi) that need to be tidied off in core.

**Comment by fosterlynn** [comment]
@pospi thanks for taking this on!  Let me know if you want thinking help.

**Comment by pospi** [comment]
Well, I got my assumptions on how `validate_agent` works all wrong, so there's a lot to think about here. I have some interesting paths to explore though, namely writing anchor entries in local chains as self-proof for future requests that agents have been registered to the public DHT space already.

**Comment by pospi** [comment]
Looking good, all the simple 1:1 relationship traversals can be done in GraphQL easily. So this is ready to merge.

**Comment by fosterlynn** [comment]
Just a little "woohoo" from the sidelines!  :heart: :heart: :heart:
