### ISSUE TITLE
Update to align with ValueFlows 0.8.0 spec

### ISSUE THREAD

**Issue by pospi** [holo-rea/holo-rea#148]
- [x] remove `AnyType` and add `__resolveType` resolvers for `AccountingScope` (may as well cover all union types while we're at it)
- [x] change use of all query endpoints to remove the `all*` prefix (probably only affects tests)
- [x] fix all deletion methods taking `String` instead of `ID` in queries (probably only affects tests)
- [ ] swap out the `URI` and `DateTime` resolvers; consider using https://github.com/Urigo/graphql-scalars. Add tests to ensure all necessary date formats are valid.

**Comment by pospi** [comment]
Split the last part of this off into #156.

**Comment by fosterlynn** [comment]
What's this?  Is that what you think hte next VF release is?  Should we attempt to realign?

>ValueFlows 0.8.0

**Comment by fosterlynn** [comment]
Deleted last comment - realized you are aligning holo-rea with vf-graphql.
