### ISSUE TITLE
Implement a generic marketplace app

### ISSUE THREAD

**Issue by pospi** [holo-rea/holo-rea#163]
Logging as a stub to track the need for a white-labelable marketplace UI that can manage trades between different platforms in economic networks.

**Comment by pospi** [comment]
Want more control over the packaging now, so splitting out to https://github.com/holo-rea/app-offers-needs-marketplace in order to workaround some limitations with Yarn monorepo handling.

**Comment by Connoropolous** [comment]
Closing on the basis of this having been split out into its own repository and sensing that capturing this here might just be cognitive overhead. Reopen if Im off base!
