### ISSUE TITLE
Implement 'stable ID' record pattern

### ISSUE THREAD

**Issue by pospi** [holo-rea/holo-rea#18]
We first need to implement a wrapper for records that allows other DNAs to detect multiple versions of the same entry as one. This allows cross-DNA linking to work predictably, but requires some wrappers to manage the underlying DHT structures in order to do so.

Basically, this means:

- de-referencing an entry's address the first time it is created and linking the actual entry data off there via an `initial_entry` link.
- creating a read wrapper function which will load the most recent version of some such record structure from the DHT by following the previously created link.
- creating an update wrapper function which follows the `initial_entry` link and updates the de-referenced entry instead of the ID entry
- creating a delete wrapper function which knows to delete both the de-referenced entry ID and linked data

Tests should prove that creating & updating a record does not result in loss of data linked to the entry ID.

**Comment by sqykly** [comment]
Whoops, I was just about to write the initial entry as `original_hash`.  `initial_entry` is fine, though.

**Comment by pospi** [comment]
Not really fussed about internal names. Call things what feels good (:

**Comment by pospi** [comment]
Steps to implementation:

- create non-DRY implementation for each structure type for a VF object: "record", "create payload", "update payload", "entry" & link definitions.
- pull up commonalities into a macro to make defining record *fields* DRY
- (may defer until later) add ability to make defining record fields *between types* DRY
