### ISSUE TITLE
Implement bidirectional links between Event.fulfills & Commitment.fulfilledBy

### ISSUE THREAD

**Issue by pospi** [holo-rea/holo-rea#20]
Following on from #19, the pattern needs to be extended to work for inter-DNA field links. It is difficult to say what the correct flow of data is for managing updates across DNAs, but one goal is for the `Fulfillment` record to exist on both sides of the network boundary. Ideally fulfillments can be managed in either network and changes would flow between them, but it may be more appropriate to only have one side of the relationship editable. We could start there and see what the added complexity in bidirectional editing looks like?

**Comment by fosterlynn** [comment]
>it may be more appropriate to only have one side of the relationship editable

The natural side to be editable is the "bottom" or "later" side.  For intents/commitments, that is commitment.  For commitments/events, that is event.  My gut is that it should be editable from only the one side.

**Comment by sqykly** [comment]
`LinkRules` is coming and will be a perfect place to refine this idea so that we can re-use it effortlessly as a pattern any time the need arises.

Why is it a goal to have the Fulfillment on both sides?  What makes it different from any other record?  Doesn't that present a security flaw, as you couldn't validate the fulfillment on the same DHT that has all the other records?

**Comment by pospi** [comment]
Not sure what you are meaning by the security flaw... you'll have to unpack that a bit more. At the end of the day if you have two different independent networks with dependent data split between them, either side can't *really* trust the other no matter which way you cut it. But what one network *can* do is facilitate being linked to by data in other networks. That means it basically has to trust / not care about the validity of the IDs of the things linking "in"; or rather, *presume* trust in that the cooperating service linking to one's own is performing honestly. In the majority of our use-cases it might even be that all such linkages are defined at installation time.

Or, think of it this way- you're linking together a bunch of apps that *you* control with identities that *you* own, and you trust those apps / networks to behave as expected in the same way that you trust the GNU command line tools to behave as expected (ie. with code signing and web of trust).

As to having `Fulfillment` on both sides- it's about record-keeping for both parties. Say you have a configuration along the lines of families managing household resources privately with their own `observation` & `planning` DNAs, but *also* connected to a neighbourhood-wide `planning` DNA so that they can coordinate resource use & waste minimisation with their neighbours. The family may not fully trust the people running the neighbourhood coop; but particularly in reverse- if the family moves away from the area and takes their `observation` network with them, the data is lost to the neighbourhood and they can't do audits as to what resources were exchanged through their network anymore. But you also don't want the family to be forced to hand over their record of events without a warrant, so you don't want their `EconomicEvent` copied to the `planning` DNA to specify the fulfillment of a `Commitment`.

The middle-ground is that the `Fulfillment` is the necessary record-keeping for *both sides*. For the family, it's a record as to how they helped their neighbour by offering something of theirs. For the neighbour, it's a record that someone from outside gifted them something. It has value as a record / an acknowledgement in both contexts; because the *interaction* was what was common, rather than the *thing* the interaction surrounded (if that makes sense).

**Comment by pospi** [comment]
Completed in #32.
