### ISSUE TITLE
economicResource doesn't respond to `name`

### ISSUE THREAD

**Issue by Connoropolous** [holo-rea/holo-rea#202]
<img width="1150" alt="Screen Shot 2022-02-25 at 6 01 37 AM" src="https://user-images.githubusercontent.com/1409121/155728117-f373e23e-c8d5-4dc4-8fb9-a2a24e2f9b8e.png">

I see that the entry itself doesn't contain it:
https://github.com/holo-rea/holo-rea/blob/25bf74aeda079569c62303070868e71e0ec5d7c9/zomes/rea_economic_event/storage/src/lib.rs#L56-L77

**Comment by pospi** [comment]
Fixed in 6c2aa53

**Comment by Connoropolous** [comment]
Nice! I was using note like name tenporarily
