### ISSUE TITLE
hREA full_suite is too large to install without switching to bundle references (instead of being fully self-contained bundle)

### ISSUE THREAD

**Issue by Connoropolous** [holo-rea/holo-rea#213]
Related was PR #193 
and the file that it added `bundles_templates/full_suite_release_template/happ.yaml`

The basic task is to: 
- [x] convert that file from being specific to the notion of 'url' based references, and making it so that it could also be filled in (as a template) with `path` based references. 
- [x] set up a little piece of automation that would perform the copy of that file locally and replace the < > string templates with the proper `path` variables for the development environment. I think (Connor) it needs to be an absolute path, not a relative one.

Background 
https://github.com/holochain/holochain/issues/966

**Comment by pospi** [comment]
Completed by updating `package-dnas.sh` script to use more env vars to conditionally toggle bundling and branch on local paths vs release download URL.
