### ISSUE TITLE
Implement REA Agent

### ISSUE THREAD

**Issue by fosterlynn** [holo-rea/holo-rea#219]
### MVP (simplest implementation)

- [x] Author a storage zome which allows any Holochain agent to store a blob of (`name` (string), `note` (string), `image` (string), `primaryLocation` (string), `type` (string)) and get back an `AgentAddress` pointing to this data. You can minimally create an `vf_attributes_hdk::AgentAddress` via `AgentAddress::new(dna_info()?.dna_hash, entry_hash)`
- [x] create `zome` `lib` and `storage` folders/crates under `rea_agent` and implement according to set patterns as can be seen in `rea_agreement` and elsewhere.
- [x] add those 3 crates into the top level Cargo.toml workspace definition
- [x] Wire it up to the query resolvers in `modules/vf-graphql-holochain/queries/agent.ts`
- [x] Implement a new agent mutation handler in `modules/vf-graphql-holochain/mutations/agent.ts` for `createPerson`
- [x] Include this zome in the DNA manifest in `happs/agent/dna.yaml`
- [x] Implement something separate for `Organization`, perhaps just a separate API endpoint which creates entries with a different "type" field. Wire this up to `createOrganization`.
- [x] #300
- [x] #311
- [x] #303 
- [x] #301 
- [x] #298

**Comment by pospi** [comment]
## Production-capable (minimum viable for ongoing usage)

What's missing from the simple MVP above is validation / ownership of profiles; and an ability to deal with updates to data.
- [ ] #297
- [ ] #133 
- [ ] #299
- [ ] add validation to prevent edits to agent profiles other than by the agent who created them
- [ ] implement a means for agents to attest that another agent key belongs to them, adding the new key to the list of keys allowed to manage an existing profile. Same can also be used to whitelist agents able to manage an organization's details.

Just an outline for now- we can refine this and split tasks out to separate issues as needed.

**Comment by pospi** [comment]
RE geolocation- it looks like there are two older efforts that might be able to be resurrected.

https://github.com/holochain-open-dev/geolocation
https://github.com/vanarchist/holochain-point-of-interest

Both would suffice- the linkage between records should be weak. Locations need to be identifiable by some unique ID, which we can then associate with other record fields (eg. `Agent.primaryLocation`). At some point we will probably also want locations to be able to be updated without that ID changing; because it's not really possible to easily track down references and change them.

In any case, it will be a standalone zome. We will also eventually want to add a companion index zome adjacent to it that foreign DNAs can manage, eg. creating `EconomicEvent`s needs to be able to update indexes for `SpatialThing.economicEvents` so that we can query all events by location. This should be easy with `hdk_semantic_indexes` macros.

**Comment by pospi** [comment]
For roles, there are also two older projects that could be resurrected, very close to providing everything that ValueFlows needs.

https://github.com/holochain-open-dev/membrane-roles
https://github.com/eyss/holochain_roles

Ideally these would be included in the agent DNA manifest and bound to the appropriate `AgentRelationship` and `AgentRelationshipRole` mutations, queries and resolvers. As with other agent functionality, it is ideal if we can use drop-in Holochain zomes to service this functionality and then perform any conversions needed to bind to VF in the GraphQL resolver layer.

**Comment by pospi** [comment]
Also want to flag that adding `EcologicalAgent` as a new subtype of `Agent` sounds like a bad idea in that it will complicate the schema in a way that adds implementation burden & complexity to all future projects (another variation in a union type which has to be handled, and has to have dedicated queries & mutations added to handle it).

I think we should think about what differentiates such an agent from an existing `Organization`. To me it sounds as though both concerns are the same-

> organizations and ecological agents, which don't want to have devices or key pairs, and don't want people logging in directly as them, since people representing them will change over time, there could be multiple people at the same time

IMO it is much better to use `Organization` for both and to use `classifiedAs` to distinguish ecological agents from other groups. As far as I can tell they have much the same behaviours and constraints when it comes to `Person` agents accessing & referencing them.

**Comment by fosterlynn** [comment]
>Implement a new agent mutation handler in modules/vf-graphql-holochain/mutations/agent.ts for createPerson

>Implement something separate for Organization, perhaps just a separate API endpoint which creates entries with a different "type" field. Wire this up to createOrganization.

>IMO it is much better to use Organization for both and to use classifiedAs to distinguish ecological agents from other groups. As far as I can tell they have much the same behaviours and constraints when it comes to Person agents accessing & referencing them.

In terms of keeping the types Person and Organization, you seem to say we could keep them separate, or not keep them separate?  Or at least lump them together internally.  I'd be fine with even ending up with just Agent on the api, with the type kept in the record so people can filter on it.  Unless you think the behavior is too different due to Person being able to have holochain agents?  I do understand there is a lot of stuff in the vf-graphql spec around the subclasses.  But I don't think Bonfire has implemented that stuff yet either.  There's one implementation with the whole VF agent model done but not out in the wild as of yet, and may not go there for awhile.  But we don't even have to think about that imo, we can just punt if you don't mind the difference with vf-graphql.

Alternatively, I do understand your thoughts about using Organization for ecological agents.  But semantically that is pretty confusing.  Some ecological agents will be individual non-human beings, for example.  I'd be fine with trying for some new name that will cover all non-human agents.  I can see if I can come up with something.  Of if we just go with Agent, this goes away.  

Also just thinking, if we want to try to work around the confusing duplication of terms with REA agent and holochain agent, we could use EconomicAgent, that is what McCarthy uses.  We just switched in vf to be able to re-use foaf and be more conformant with the semantic web community.  I think it will be worth it to use a name for now that isn't "agent", until the concept maybe eventually becomes implemented cross-technology-ecosystem, which will be awhile I think.  Also, that will be also broader than vf, so will be a whole new standards effort. :)

Summary:  Seems to me the easiest, cleanest is to implement EconomicAgent with a type field. But you are close to how the code works, so maybe I'm wrong. @pospi

**Comment by pospi** [comment]
Hmm, good points. A type field is still an extension to the FOAF spec, though.

Chatting to @Connoropolous about it yesterday, it sounds like if we build to the FOAF and Organization vocabs then we will end up with something more generally applicable than VF Agents, which other apps besides hREA might want to make use of. That seems advantageous; and potentially a way that other orgs like Lightningrod Labs might take on the work (since they already started on "[we](https://github.com/lightningrodlabs/we/)").

Looking at the spec, it seems like re-abstracting `Agent` back into purely `Agent` without any sort of `Person` or `Organization` distinction might be a great way to go. My understanding of where Bonfire are at is that they have additional complexity to debate about distinguishing agents-with-economic-agency from simple-groups-of-humans-without-agency. Again, all this goes away if we simply deal with `Agent`. Curious to hear what @mayel @ivanminutillo and @srfsh might think about that.

Currently the only real difference is that `Organization.classifiedAs` is a field, which does not exist on `Person`. So... `Person` could easily just have `classifiedAs = foaf:Person`? Do we really need a type field at all? Or maybe there are fields from the external RDF specs that have not been considered in the GraphQL schemas yet. Either way it presently seems like a lot of unnecessary extra API endpoints and datatypes for little distinction. Unifying the two would also allow the `AccountingScope` union to go away, which removes a little more implementer burden.

Another possible advantage for future works (not for hREA though) is that `myAgent` could be an organization or any other type, more natively enabling nodes in a network to act as organisational entities.

**Comment by pospi** [comment]
Posting as a separate reply so as to not add noise for the non-Holochain folks: 

- [ ] we will also need some kind of "whois" function on the REA Agent zome that accepts a Holochain-native `AgentPubKey` and returns either a full `Agent` record, or a `(DnaHash, EntryHash)` tuple identifier for the associated agent record.

Besides resolving the necessary incompatibilities between other Holochain zomes which might identify agents in this way and the REA layers of a system, this also has an advantage in configurations where the `AgentPubKey` differs on a per-DNA basis&mdash; you *can* feasibly have a different `AgentPubKey` in *Observation* than in *Planning*, and these divergent IDs could all be registered to the same REA Agent and resolvable internally in the GraphQL layer without app developers having to think about it.

**Comment by fosterlynn** [comment]
Thoughts in response:

>it sounds like if we build to the FOAF and Organization vocabs then we will end up with something more generally applicable than VF Agents

Yes, if we can build something with more potential for universality in the future, without impacting schedule, that would be ideal.  (VF does use foaf and org anyhow.  I just suggested EconomicAgent or REAgent to try to not conflict with hc agent, as a "punt" not a universal solution.)

>A type field is still an extension to the FOAF spec, though.

AFAIK that kind of thing doesn't cause any pain for RDF people really, they do a lot of mix and match.  They just have to be defined properly inside a vocabulary, which we can do.

>Looking at the spec, it seems like re-abstracting Agent back into purely Agent without any sort of Person or Organization distinction might be a great way to go. 

I'm getting more and more attached to that myself!  Even for VF, as soon as we could make it not too much of a breaking change.  Now actually might be the best time for that, with apologies to Basis Project and Web of Needs, I could check with them.  It would currently be Bonfire, Reflow, hREA, I think.  FabCity isn't far enough along, might have a very small correction to do.  Also, @srfsh and I were having a discussion along these lines this morning because the VF-graphql and relational db mismatch is so annoying.

>My understanding of where Bonfire are at is that they have additional complexity to debate about distinguishing agents-with-economic-agency from simple-groups-of-humans-without-agency.

That is true, and there are even more issues vs existing apps.  They have implemented user, an account can have more than one user, and you can put an organization in as an additional user... and then they added a way for other users to join the organization. I think I have that right, I'm sure @mayel can correct me if I'm wrong.  To my knowledge, that has always been temporary, but we haven't discussed it lately, hasn't been a priority for them.  It occurs to me that dropping back to just Agent might help with the VF/foaf agent / ActivityPub actor integration, because AP already has Person, Group, Organization as types of actors.

>Currently the only real difference is that Organization.classifiedAs is a field, which does not exist on Person. So... Person could easily just have classifiedAs = foaf:Person? Do we really need a type field at all?

Since classifiedAs is currently a pretty loose thing elsewhere in the vocab, without firm members to the set, maybe we do both?  Have just foaf:Agent, with a well-defined list of vf:type (or better name) that will matter to behavior (Person, Organization, EcologicalAgent right now - maybe Group to conform to a lot of RDF vocabs), plus vf:classifiedAs for users to use for more specific definitions they want to call out (cooperative, open value network, ecosystem, ....).  If foaf has some classifiedAs kind of property, we could use that (they already have the subclasses though)

We would still have the issue of naming vs the hc agent though.... hmmm.

**Comment by pospi** [comment]
I think it'd be great to go ahead with this now. Maybe check with Basis & WoN, then submit a PR to the core vocab as a starter to gather feedback?

I suggest these particulars, based on what you've said and my non-ontologist naive experience of RDF grammars:

- Add `vf:agentType` to as a field valid for `foaf:Agent` (`vf:type` feels too generic)
- Possible values for `vf:agentType` being `foaf:Agent`, `foaf:Person`, `foaf:Organization`, `foaf:Group` and a new `vf:EcologicalAgent`
- make `vf:EcologicalAgent` a new subclass of `foaf:Agent`? Would this mean `vf:agentType` only needs to be defined as a valid subclass of `foaf:Agent`?

**Comment by fosterlynn** [comment]
Results of a meeting between @pospi @bhaugen and me, please let us know of any disagreements @Connoropolous or anyone!

The VF core spec won't change, at least as of now, that is more complicated.  If hREA needs to spit out data to apps in other technical ecosystems using more semantic web based formats, we could create the subclasses if needed.  And maybe by that time, VF would be just "Agent".  (We can initiate some discussion with other projects about the graphql layer changing, but we didn't address that in the meeting.)

In hREA, we will create a new zome for Agent, fields: agentType (with the list in the last comment from pospi), name, note, image.  NYTL will use the note field for now to keep formatted longitude/latitude, and parse it for that piece of Agent.primaryLocation data.  Note we thought that using the name Agent would be OK.

We'll also create a 1:M link between Agent and the holochain agent pubkey (and whatever other info is kept).  The holochain agent pubkey (is that the right id?) is will be what is stored in the metadata for who saved a record in hREA.  The Agent id will be what is stored whenever an Agent is referenced in the app (provider, receiver, etc.).

Please correct me or make additions as needed, pospi!

**Comment by pospi** [comment]
I think that's about right. However given that this is temporary and will evolve as project needs will I don't think there is any issue in putting non-spec-compliant fields in- why do some weird thing with `note` for location when we could just add `primaryLocation` to store a lat,lng coordinate as a string? We can hide away any weirdness in the GraphQL resolvers to make whatever internal data format we use for Agent record storage in Holochain conform to the GraphQL spec at query time.

**Comment by fosterlynn** [comment]
>why do some weird thing with note for location when we could just add primaryLocation to store a lat,lng coordinate as a string?

sure, much better!

**Comment by fosterlynn** [comment]
I was also thinking about agent relationships and roles this morning.  Either they will need to be not far behind this, or we could do another hack.  For example, in NYTL, they will want to see farms vs mills vs designers, etc. maybe color coded, maybe filterable, etc.  Those would be roles in the network. But as long as those agents don't have multiple roles, we could add classifiedAs and use that for now.  I'll check with them.

And we can see where the rest of the VF agent model will fall in the priorities, as that shakes out.  If we will not be doing a hack on Agent itself, this can go into another issue.

**Comment by Connoropolous** [comment]
@pospi we need to flush out a plan for `myAgent`. 
Wesley and I chatted and proposed that `createPerson` may need a field (boolean) with which to indicate if the Person Agent being created should be affiliated with the AgentPubKey creating it, such that when you would call `myAgent` it would do a `get_links` and filter by a tag that would have been set during the creation process. What do you think?

**Comment by Connoropolous** [comment]
I see now your prior comment on it here https://github.com/h-REA/hREA/issues/219#issuecomment-1079577254

**Comment by pospi** [comment]
> may need a field (boolean) with which to indicate if the Person Agent being created should be affiliated with the AgentPubKey creating it

I'm kindof of the opinion that this should always be done, and that agents are therefore always responsible for registering their own profiles.

In the case of someone making an agent profile for somebody (or more importantly, some*thing* else); they could always delegate ownership to a different `AgentPubKey` via a separate API method.

There is an awkward constraint here that `whois(some_agent_pubkey)` must be unique for each `some_agent_pubkey`; i.e. an agent can't have more than one "primary" profile they are identified by or else we can't reliably know who is who. Maybe this could be validated by enforcing that only one `Person` agent can be associated with an `AgentPubKey`? Then multiple keys could still be assigned to `Organization` and `EcologicalAgent` profiles, and checks could be made as to who has permission to act on their behalf, but those agents would not be considered "the agent" of any `AgentPubKeys` authorized to act on their behalf.

Keeping in mind too that no hREA records will ever reference an `AgentPubKey` directly, which means that REA agent profiles shouldn't encounter any difficulty or complexity in being linked outside of this module.

**Comment by fosterlynn** [comment]
A couple things to double check.

>I'm kindof of the opinion that this should always be done, and that agents are therefore always responsible for registering their own profiles.

Makes sense to me.

Noting that eventually, a Person type Agent will need to be able to have multiple holochain profiles / pubkey identities (for their different devices).  We don't need it right now, but it would be good to not preclude it with the data structure we put into place now.

>Then multiple keys could still be assigned to Organization and EcologicalAgent profiles, and checks could be made as to who has permission to act on their behalf, but those agents would not be considered "the agent" of any AgentPubKeys authorized to act on their behalf.

I hope I understand what you are saying, apologies if not.  Can I suggest a slightly different model? 

![agent-pubkey](https://user-images.githubusercontent.com/3776081/173085129-4e1439cb-90f3-4310-bf52-e53fc5d0ac3d.png)

**Comment by Connoropolous** [comment]
> I'm kindof of the opinion that this should always be done, and that agents are therefore always responsible for registering their own profiles.

Ok, I hope it works, and that we don't run into real-world limitations where people aren't able to be onboarded, but it would still have been useful to represent them in the system. I can roll with this for now

**Comment by Connoropolous** [comment]
Your second diagram makes sense and seems like a clear and good model to me Lynn

**Comment by Connoropolous** [comment]
I am also just re-noting that Lynn wrote this in her original comment: 
"Note that some REA Agents needed in holo-rea won't be in the DNA network, or even be in the holochain ecosystem (yet!). Like outside suppliers, for example. But they will still need to be recorded so they can be used."

**Comment by fosterlynn** [comment]
>Ok, I hope it works, and that we don't run into real-world limitations where people aren't able to be onboarded, but it would still have been useful to represent them in the system. I can roll with this for now

>I am also just re-noting that Lynn wrote this in her original comment:
"Note that some REA Agents needed in holo-rea won't be in the DNA network, or even be in the holochain ecosystem (yet!). Like outside suppliers, for example. But they will still need to be recorded so they can be used."

I wasn't think about this above.  So, what to do about people (and organizations too I think) that are needed as data by a network.... but then might be needed as data by another network too.... and then might join holochain as a person or set up a suite of apps as an organization?  But they're already in the ecosystem as "other people's" data.  I'm not thinking of any simple solutions, so maybe we just let it be like it is on siloed apps, where different apps or instances have different records for the same agent?  Given we are doing a simple Agent as "part of" hREA to get things up and running, rather than try for a holochain-wide solution right now, I guess this follows from that.  All in good time.... 

[edit]  I would think that having a person agent record somewhere wouldn't preclude someone from onboarding themselves, there just might a duplicate name somewhere, which can happen for different people too.

**Comment by pospi** [comment]
> what to do about people (and organizations too I think) that are needed as data by a network.... but then might be needed as data by another network too.... and then might join holochain as a person or set up a suite of apps as an organization?

Good point. I guess the assignment of the requesting `AgentPubKey` will have to be an optional step then. It could be done automatically for the first profile creation and not done if an existing profile exists? But that feels iffy. May be best to have 2 separate API endpoints after all.

Another possibility: another agent type for `ExternalAgent` which does not do the profile assignment like `Person`. And an API endpoint along with that for something like `claim_agent` which would take an existing `ExternalAgent`, convert it to `Person` and assign the `AgentPubKey` of the requestor as its authority? Or would it make more sense if the agent who originally created the record was the only one able to assign it?

**Comment by pospi** [comment]
@weswalla a couple of notes from today's call, just for completeness.

- We will do a first PR of just profile storage and tests for agent CRUD before we move on to implementing relationships and queries in #298 & #299. 
- Leave `inScopeOf` for now, we'll implement separately in #297

**Comment by fosterlynn** [comment]
>Another possibility: another agent type for ExternalAgent which does not do the profile assignment like Person.

That doesn't sound so much like an agent type, as perhaps something we could capture in RoleBehavior or something else around agent relationships.  

>I guess the assignment of the requesting AgentPubKey will have to be an optional step then. It could be done automatically for the first profile creation and not done if an existing profile exists? But that feels iffy.

Given the range of possibilities, can we just let the logged-on person (pubkey) decide what has to be done?  And offer the choices?  Or maybe think of it as completely different features in the UX: 

* I'm a person agent setting myself up, and yes this is my pubkey.  
* I'm this other agent and this is yet another of my pubkeys, maybe connected to the previous one, and maybe not a priority right now.
* I'm just creating other non-human or external human agents for this network right now.  Completely separate activity than setting myself up in the app.

**Comment by Connoropolous** [comment]
I'm closing this one and have shifted out the bigger scope of work into the backlog as #313
