### ISSUE TITLE
Time-ordered listing & indexing

### ISSUE THREAD

**Issue by Connoropolous** [holo-rea/holo-rea#220]
Implement reliable, DHTops-friendly means of retrieving a time-ordered list of records, and order records by creation time. (suggest [this lib](https://github.com/holochain-open-dev/holochain-time-index))

- #268 
- #331

**Comment by pospi** [comment]
A more complete set of requirements for this, given a page size of N:

- *All* query APIs must return records in a consistent sort order, no matter the query parameters provided
- Different ordering will need to be done independently of the query parameters

(and per #85, but should be considered now)-

- Pagination must work as expected (starting record given by its ID and able to read N records forward)
- Paginating should return N records or fewer (if difficult it can return >N, but probably we can do this simply by truncating results)

**Comment by Connoropolous** [comment]
I've moved the details from the last comment  above over to the relevant issues
#85 for pagination
#331 for ordered data for queries

with that I'm going to close this one, it feels redundant and dilutes the clarity
