### ISSUE TITLE
Abstractions for list output handling

### ISSUE THREAD

**Issue by Connoropolous** [holo-rea/holo-rea#221]
Abstract away list output handling into `hdk_records` (or potentially a new library crate) so that each individual zome can do things less verbosely.

**Comment by pospi** [comment]
It's now added inline by the `index_zome` proc macro. Since it's only used at the zome API boundary, this seemed like a sensible architecture. Close if you agree (:

**Comment by Connoropolous** [comment]
since it follows with the other conventions, happy to roll with it for now 👍

**Comment by Connoropolous** [comment]
or should it be closed when #268 is merged I guess

**Comment by pospi** [comment]
There is a little more to do in addition to that, need to finalize the `Cursor` handling & test pagination

**Comment by pospi** [comment]
Actually, fine to close this. #222 tracks cursor-related stuff.
