### ISSUE TITLE
create a piece of reference documentation for which DNAs encapsulate which VF modules

### ISSUE THREAD

**Issue by Connoropolous** [holo-rea/holo-rea#235]
The best thing going so far is this: https://docs.google.com/spreadsheets/d/1bbp896cA6rc9A3OTCOfIn0DMYL-EoulXG2W90zG6oWw/edit#gid=0

But I'd like something that elucidates the rationale as well

**Comment by Connoropolous** [comment]
this has gotten better

**Comment by pospi** [comment]
How are you thinking of documenting this at present? I figured the code would sorta be self-documenting now since there should be two sets of module IDs configured & mapped somewhere, but if you see the need for something to be elaborated on in fulltext let me know.
