### ISSUE TITLE
Permission denied.

### ISSUE THREAD

**Issue by Thystler** [holo-rea/holo-rea#238]
While trying to run the "sudo npm i" in the main launcher i get the following error.

npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/holochain/admin-ui.git
npm ERR! 
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 

after a large number of warings about
[hello.log](https://github.com/holo-rea/holo-rea/files/8397701/hello.log)
 
Is this a mistake that i am making?

**Comment by Connoropolous** [comment]
What do you mean by the "main launcher"?

**Comment by Thystler** [comment]
So I am running from the folder where the holo-rea is located. 
_nix-shell
npm i_

And this returns the error

npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://[git@github.com](mailto:git@github.com)/holochain/admin-ui.git
npm ERR!
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!

The full log of this is found in hello.log

Thanks for your response

**Comment by Connoropolous** [comment]
you should be running `pnpm i`

**Comment by pospi** [comment]
If you still get the error with `pnpm i`, a logfile would be useful. You should be getting a different error message with `npm i`, and the one you're getting looks like a Github authentication issue. Which is weird- we aren't referencing that repo directly at all, but possibly one of the core Holochain modules does in which case we should file it upstream.

Thanks!

**Comment by Connoropolous** [comment]
This issue seems out of context. It seems like it has to do with the Holochain Launcher (which uses admin-ui). I am closing for now. @Thystler please let us know if there's more clarity we can have on this.
