### ISSUE TITLE
make `mapZomeFn` take generic parameters so that we have compiler guarantees at API boundary

### ISSUE THREAD

**Issue by pospi** [holo-rea/holo-rea#270]
- [ ] make the function accept generic arguments for the input and output type
- [ ] for each `mapZomeFn(...)` call import the relevant types and reference them

Not sure if this is the moment, but noting that I'd like to make `mapZomeFn` take generic parameters so that we can define both the expected input type and the expected output type. 
That would mean we'd be able to have type checking and type safety on this line where we write `(...).plan` and it's so opaque why there is a property called `plan` on this data structure. 

e.g. it might look like `mapZomeFn<InputType, OutputType>(...)`

_Originally posted by @Connoropolous in https://github.com/h-REA/hREA/pull/269#discussion_r880052534_

Related code: 
https://github.com/h-REA/hREA/blob/459c8c98e224a3330350a38ac6b0c9178dab88df/modules/vf-graphql-holochain/connection.ts#L266-L296

Instead of having the 'explicit type loss' we can retain type information where/when we have it, and write `<any, any>` in the worst case scenario of not knowing the types (which... should never happen)

**Comment by Connoropolous** [comment]
closed in #280
