### ISSUE TITLE
rename zome names which have prefix `rea` with `hREA`

### ISSUE THREAD

**Issue by Connoropolous** [holo-rea/holo-rea#272]
there are names such as `rea_unit`

**Comment by pospi** [comment]
I think all zome names were `rea_`. There shouldn't be any `hREA` ones; and I also don't think Rust likes you putting uppercase in crate names. Anyways, the reason for this decision was that the "Holochain" part felt already implied by the `hc_zome_` crate prefix; thus- `hc_zome_rea_XXX`.

**Comment by pospi** [comment]
@Connoropolous how are you feeling about this one, should we action it or leave them as they are? Curious to hear which ones *aren't* named "rea_"- if it's just the agent zomes I do think that makes sense (since that's more FOAF than REA).

**Comment by fosterlynn** [comment]
>Curious to hear which ones aren't named "rea_"- if it's just the agent zomes I do think that makes sense (since that's more FOAF than REA).

I don't have an opinion on the general question, but I wouldn't worry in general about which rdf-based vocabulary something came from.  REA needs agents as much as resources and events, we just made an effort to re-use in the context of rdf, semantic web, which doesn't have much to do with holochain and won't make sense to people.  For that matter, there isn't any "REA", just "VF".  And FOAF doesn't have the agent relationship piece of the agent model.  Etc.  

Although, if you think the agent zome might be pulled out and used across holochain, maybe that's a reason to prefix it with something else if you want?  Units might fit that too.  But I don't know the holochain culture/guidelines around that question.
