### ISSUE TITLE
After release of the first HDI (or integrity kit) of Holochain, update versions to that

### ISSUE THREAD

**Issue by Connoropolous** [holo-rea/holo-rea#275]
here is an example to sample from: 
https://github.com/perspect3vism/agent-language/tree/main/hc-dna/zomes/tests

**Comment by pospi** [comment]
This will be quite an extensive refactor- we will need to update all the index handling logic to use split integrity/coordination zomes to manage the updates via `post_commit` hooks. In doing so it is hoped that such cascading updates can be handled more gracefully, and `debug!` statement related to indexing removed.

We may also have to update tests unrelated to Agent data but featuring Agent links to actually create the agents in question. Currently the indexing situation swallows / ignores many `CellMissing` errors that are related to mocked `AgentAddress`es.

**Comment by Connoropolous** [comment]
"we will need to update all the index handling logic to use split integrity/coordination zomes to manage the updates via post_commit hooks. In doing so it is hoped that such cascading updates can be handled more gracefully, and debug! statement related to indexing removed."

This sounds like added scope. Unless I'm missing something which is very possible, this sounds like something unnecessary to do at this same time. Can we trim back this scope to only the update?

I am thinking of targeting HDK 0.0.142
HDI 0.0.14

And thats Holochain 0.0.150

**Comment by Connoropolous** [comment]
"We may also have to update tests unrelated to Agent data but featuring Agent links to actually create the agents in question. Currently the indexing situation swallows / ignores many CellMissing errors that are related to mocked AgentAddresses."

I also don't think we will have to do this.

**Comment by pospi** [comment]
Yeah, two phases for these updates I think.

**Comment by Connoropolous** [comment]
@pospi I've started this, and have assigned it to myself for now, but am also happy to collaborate on it, we would just need to coordinate our actions.

**Comment by Connoropolous** [comment]
There is this one to review: https://github.com/holochain-open-dev/dna-auth-resolver/pull/3
and this one is up and just getting started in draft: https://github.com/h-REA/hREA/pull/340
