### ISSUE TITLE
update the Plan DNA and tests with `plannedWithin` field that was previously missing

### ISSUE THREAD

**Issue by Connoropolous** [holo-rea/holo-rea#278]

**Comment by Connoropolous** [comment]
@pospi I think this is contingent on you or I adding `plannedWithin` to `CreatePlanParams` and `UpdatePlanParams` over in v-graphql, agreed?

**Comment by pospi** [comment]
No, those fields aren't writable via `Plan`. The relationship on that side is `processes`- what needs to be checked is that creating a `Process.plannedWithin` updates the reciprocal index `Plan.processes`, and that both sides of the query return the correct results.

**Comment by Connoropolous** [comment]
Ah. I expressed this wrong, sorry. 

I meant to be referring to `Commitment` and its relationship with `Plan`. That is the `plannedWithin` that I was concerned with, and we (Wesley and I) were wondering if it shouldn't be the case that `CommitmentCreateParams` and `CommitmentUpdateParams` should have the `plannedWithin` field, which appears to be missing: https://lab.allmende.io/valueflows/vf-schemas/vf-graphql/-/blob/sprout/lib/schemas/bridging/commitment.plan.gql#L29-37

**Comment by Connoropolous** [comment]
@fosterlynn you also might be able to help us on this?

**Comment by fosterlynn** [comment]
>we (Wesley and I) were wondering if it shouldn't be the case that CommitmentCreateParams and CommitmentUpdateParams should have the plannedWithin field, which appears to be missing

Makes sense to me.

**Comment by Connoropolous** [comment]
Ok that being the case I submitted a PR here, and requested @pospi review on it. Thanks @fosterlynn 
https://lab.allmende.io/valueflows/vf-schemas/vf-graphql/-/merge_requests/107

**Comment by pospi** [comment]
Done! `0.9.0-alpha.5` now published

**Comment by Connoropolous** [comment]
@weswalla 
this is actionable now. There's a release of vf-graphql (0.9.0-alpha.5) that Pospi just did, that if updated to, contains the `plannedWithin` field for `CreateCommitmentParams` and `UpdateCommitmentParams`.
