### ISSUE TITLE
update tryorama to 0.5.4 - new syntax

### ISSUE THREAD

**Issue by Connoropolous** [holo-rea/holo-rea#290]
this will help us unravel some of our little shims that we've added to fix tryorama ourselves

https://www.npmjs.com/package/@holochain/tryorama/v/0.5.4

**Comment by Connoropolous** [comment]
@pospi this is something we'd have likely wanted to do anyways, but it also is maybe a dependency for #291 which I'm pretty keen on. 

I can take this action if you have no disagreement

**Comment by pospi** [comment]
None at all, go for it

**Comment by Connoropolous** [comment]
Ok cool, I will

**Comment by Connoropolous** [comment]
@pospi 
seeking your recommendation on something... 

After updating some dependencies, including `tape` I am getting an error on a deepEqual comparison. 

The contents are fine, but it seems to be failing because of an `Object: null prototype` on the object of the Graphql response. This seems to be a known thing. 

I tried the proposed solution, which I don't much like, of `JSON.parse(JSON.stringify(graphqlresponse))` but that meant a date time mismatch in the two, afterwards. I would have to use `JSON.parse(JSON.stringify(...))` on both the actual and the expected but this feels slow and ugly. Any recommendations?

https://stackoverflow.com/questions/53983315/is-there-a-way-to-get-rid-of-object-null-prototype-in-graphql

```
not ok 2 record read OK
  ---
    operator: deepEqual
    expected: |-
      { id: 'uhCEkA0DPdYdXWl13nIWuD7hSRYGOoSbfbhnjIW5dIhZzVvw6alz3:uhC0kPbuO-_JcsF_2v5hSVz55wM0zmD-9mFaBq93Y4SSNCZR5ffa7', revisionId: 'uhCkkR2enkXTv7jKbpaZYvYVolC7LEsXt-xGK6YuOxO9m28nWhco-', name: 'test agreement', created: Sun Jun 12 2022 18:27:36 GMT-0700 (Pacific Daylight Saving Time), note: 'just testing, nothing was rly agreed' }
    actual: |-
      [Object: null prototype] { id: 'uhCEkA0DPdYdXWl13nIWuD7hSRYGOoSbfbhnjIW5dIhZzVvw6alz3:uhC0kPbuO-_JcsF_2v5hSVz55wM0zmD-9mFaBq93Y4SSNCZR5ffa7', revisionId: 'uhCkkR2enkXTv7jKbpaZYvYVolC7LEsXt-xGK6YuOxO9m28nWhco-', name: 'test agreement', created: Sun Jun 12 2022 18:27:36 GMT-0700 (Pacific Daylight Saving Time), note: 'just testing, nothing was rly agreed' }
    stack: |-
      Error: record read O
```

**Comment by pospi** [comment]
Hrmm. Is it doing this for all object comparisons, or just some? If some, specifics would be good so I can investigate further. Maybe it only affects comparisons made on the toplevel object response?
I do recall seeing these prototypes before, but they weren't causing errors previously for some reason.

Also curious whether `require('assert').deepEqual` gives the same result, or we might shim it into Tape?

**Comment by Connoropolous** [comment]
between the version of `tape` I upgraded from, and the version I upgraded to, `deepEqual` became strict by default, when it previously wasn't. I was able to repair the issue, after some digging, by using `deepLooseEqual` in its place
