### ISSUE TITLE
documentation on DNAs and ValueFlows "Modules" needs updating now

### ISSUE THREAD

**Issue by Connoropolous** [holo-rea/holo-rea#293]
- [x] #294

To reflect this:
https://lab.allmende.io/valueflows/vf-schemas/vf-graphql/-/merge_requests/105

**Comment by pospi** [comment]
Might be worth splitting the wiki page documentation update into its own issue, for doing once we hit the MMR milestone? I don't see anything in there that really mentions VF modules, so there's nothing much to update in that respect. But the whole page needs a going-over at some point and checking for accuracy based on the final delivered product.

**Comment by Connoropolous** [comment]
Ok I've separated the two and made sub-issues. 

"I don't see anything in there that really mentions VF modules"
Can you expand on this perception? The whole thing seems to be an explanation of `VfModule` in a way, no? Or are you seeing it as an explanation of the way the DNAs are sitting, and configured, and you're using the word "Module" to refer to that as well. ?

**Comment by pospi** [comment]
> are you seeing it as an explanation of the way the DNAs are sitting

Yes, exactly. There is nothing in that document to do with VF-GraphQL at all, it's entirely about the hREA DNA organisation. And depending on how flexibly we end up packaging them it might not actually make sense to talk about DNAs at all in the end? But we will see...

**Comment by Connoropolous** [comment]
Yeah ok. At least I know what is meant for that section. Thanks!
