### ISSUE TITLE
Implement simple inverse queries of `provider` and `receiver` on agent records

### ISSUE THREAD

**Issue by pospi** [holo-rea/holo-rea#298]
A [PR to VF GraphQL](https://lab.allmende.io/valueflows/vf-schemas/vf-graphql/-/issues/100) has to be made first before any of the simple [inverse query edges](https://www.valueflo.ws/specification/inverses/) can be implemented.

You can ignore
- any fields involving `X.inScopeOf` for now, pending #297 
- any fields involving `EconomicResource.primaryAccountable` for now, pending #133 

This only includes "inverse queries", not "other queries".

The focus here is:
`Commitment.provider` and `Commitment.receiver`
`Intent.provider` and `Intent.receiver`
`EconomicEvent.provider` and `EconomicEvent.receiver`

- [ ] comment out [the lines so far in `Agent`](https://github.com/h-REA/hREA/blob/5f01158a78266d4c0e96b8ff34a3a0047f0a7b1f/modules/vf-graphql-holochain/resolvers/agent.ts#L46-L85) which will be uncommented later in #297 and #133
- [ ] add `Agent.commitmentsAsProvider`
- [ ] add `Agent.commitmentsAsReceiver`
- [ ] add `Agent.intentsAsProvider`
- [ ] add `Agent.intentsAsReceiver`
- [ ] add `Agent.economicEventsAsProvider`
- [ ] add `Agent.economicEventsAsReceiver`

### For `Commitment.provider`:
We will need these to be implemented:
https://github.com/h-REA/hREA/blob/5f01158a78266d4c0e96b8ff34a3a0047f0a7b1f/zomes/rea_commitment/zome_idx_planning/src/lib.rs#L35-L36

### For `Intent.provider`:
we already have
https://github.com/h-REA/hREA/blob/5f01158a78266d4c0e96b8ff34a3a0047f0a7b1f/zomes/rea_intent/zome_idx_planning/src/lib.rs#L30-L32
and
https://github.com/h-REA/hREA/blob/7e3d5ad7a0849f8c4996d9c767ce64c486058870/zomes/rea_intent/lib/src/lib.rs#L37-L42

is it then just a matter of hooking up the resolver function? Is this relationship tested?

**Comment by pospi** [comment]
Sorry for the delay on this @weswalla, I had an enormous document of inverse relationship names to work through and I wanted to make sure I'd done some thorough QA on them in the process.

Should probably have just done the "agent" ones as a release before doing all that, but oh well. `0.9.0-alpha.6` is now published and should have everything you need.

**Comment by pospi** [comment]
@Connoropolous was there any other reason to limit this issue to the discussed fields above, or can we go ahead and implement every relationship for `Agent` that targets the other record types we've already implemented?

**Comment by Connoropolous** [comment]
I was just looking at which parts are the most implemented already, and separating the scopes of work, so as to get smaller PRs and easier to reason about and read.
