### ISSUE TITLE
for `createPerson`, allow to associate the current users AgentPubKey optionally with the person being created

### ISSUE THREAD

**Issue by Connoropolous** [holo-rea/holo-rea#302]
on the holochain side, do this by creating a link between the current users AgentPubKey and the newly created Agent entry, by its address.

**Comment by weswalla** [comment]
can I assume there is some boolean flag passed in to the zome function, something like `link_pub_key: boolean`? @Connoropolous

**Comment by Connoropolous** [comment]
yes that's right

**Comment by Connoropolous** [comment]
for now, just trial it by hardcoding the underlying inner zome call, in the mutations code

**Comment by pospi** [comment]
Would it be possible to also have it as an independent API endpoint? The flag can stay, or not- unfussed. That way newcomers can claim already-existing profiles and the like.

I suppose we also need some validation to prevent more than 1 profile being linked to the same `AgentPubKey`, but I'm guessing that's already done (just mentioning for completeness).

In addition to the validation, a useful behaviour might be to clear any existing association before setting up a new one when this "independent API endpoint" is called to make a profile association. That would be an easy way to facilitate folks updating their profiles with new data.

**Comment by Connoropolous** [comment]
"I suppose we also need some validation to prevent more than 1 profile being linked to the same AgentPubKey, but I'm guessing that's already done (just mentioning for completeness)."
That validation isn't going to be possible, due to network partitions. We can't validate that kind of thing it's non-deterministic.

The most useful way to handle this is on the "read" side, not the "write" side I think. It might even be more accurate to make `myAgent` return an array. I'm not sure we can enforce singularity, or if we do, it's superficial. I guess we can enforce singularity within a single agents source chain. We just can't enforce singularity across the DHT.

**Comment by Connoropolous** [comment]
@pospi if we do it with a separate API endpoint, how do we create a graphql layer for that, since its not in the Vf Graphql spec?

**Comment by pospi** [comment]
Please see https://github.com/h-REA/hREA/issues/311#issuecomment-1164308123 in answer to the above :slightly_smiling_face:

**Comment by Connoropolous** [comment]
closing this issue, as we are deciding to go with #311 instead
