### ISSUE TITLE
GraphQL explorer interrupted with error popup after Webpack upgrade

### ISSUE THREAD

**Issue by pospi** [holo-rea/holo-rea#315]
Looks like (absence of) the use of polyfills has caused the Holochain web client to break-

![image](https://user-images.githubusercontent.com/437540/176357889-a95f3fb1-a05f-4234-80b4-57b60c0fd825.png)

**Comment by Connoropolous** [comment]
I'll get on this tomorrow. In the meantime I do believe you can close it and access it. At least on mine you could.

**Comment by Connoropolous** [comment]
I've logged these issues (see above) and tried quite hard this morning to provide a fix. At the moment I can't find my way through one. 

I will circle back once I hear more from others, on the issues logged

**Comment by Connoropolous** [comment]
sorry about the open/closing issue. 
It keeps happening to me that I use `Command + Enter` to add my comment but that now seems to close the issue when previously it would just leave a comment

**Comment by pospi** [comment]
hah, thanks Microsoft :stuck_out_tongue_winking_eye: 
Thanks for taking a look for me, sorry I keep bumping into trivial things and thinking they are more severe than they are! I was actually getting a white screen on closing the popup but this turned out to be due to outdated NPM dependencies.

**Comment by Connoropolous** [comment]
This commit will fix this issue, though for now it points to a fork

https://github.com/h-REA/hREA/pull/340/commits/3a6365e38e83850a3ed902620a94fa70df1b3e76

getting it back off the fork and depending on @holochain/client will require us to resolve: https://github.com/holochain/holochain-client-js/issues/116

**Comment by Connoropolous** [comment]
I updated sprout to include a forked version of @holochain/client @ 0.4.3 version

So that fixes this for now.
