### ISSUE TITLE
update_index macro removes extra indexes

### ISSUE THREAD

**Issue by weswalla** [holo-rea/holo-rea#318]
In implementing #316, I think I may have come across a bug (or I'm not using `update_index` properly). In the tests here https://github.com/h-REA/hREA/blob/feature/133-economic-resource-primary-accountable/test/agent/test_economic_resource_primary_accountable.js 

I create two economic resources, which at first are both associated with bob as primaryAccountable. bob.inventoriedEconomicResources returns both of these. But then, when I update the index in a transfer event to make Alice the primaryAccountable of one of these resources, it seems that both indexes for bob get deleted, rather than just the one.

One hint at the problem came from rust feedback as well:
```
Jul 01 15:24:59.368 DEBUG wasm_trace: hc_zome_rea_economic_resource_lib:zomes/rea_economic_resource/lib/src/lib.rs:138 update_economic_resource::to_resource_inventoried_as::primary_accountable index Ok([Ok(RemoteEntryLinkResponse { indexes_created: [Ok(HeaderHash(0x842924b52e4f7d691860151689011e07a07751be497afed5f8b5281a49fac67668610151cb966b)), Ok(HeaderHash(0x84292417b60e1e18d875c55aadc981159b545bd8e62900507a7f93e93c39f5ce3418bb6d8e00c2))], indexes_removed: [] }), Ok(RemoteEntryLinkResponse { indexes_created: [], indexes_removed: [Ok(HeaderHash(0x842924b6e2b4c4c57b542a19530acbc1d24484db32a238bffa9216676fde358412e7c1b89339a8)), Ok(HeaderHash(0x842924e08a6356ecfa5520beaf0af9bea1c1c774927f2edc70aad997d76e8019d08efa40497bf1)), Ok(HeaderHash(0x8429240f2113f720d1e5fe77107aa647392591746aba782159405ce77f749ad8b948cfc4de32cc)), Ok(HeaderHash(0x842924ba0517db835a76238e01b7b8e88b7f1fc1b2755a1046209e4c70ed5a0a2df14ddf424efd))] }), Ok(RemoteEntryLinkResponse { indexes_created: [Ok(HeaderHash(0x842924f99cfdfdf2e7dd8e3dd89304d5ba78b9e77cc3eb1cec819ecfb9390c1262bb88ae7dc41b)), Ok(HeaderHash(0x8429243ce09e75e8837bb3e8e9eaba107cd126719762c785c919855fa948cd29b5b61fe257558e))], indexes_removed: [Ok(HeaderHash(0x84292415c5b429e31bcf86f53d1ea3582f4dd3ac76f97e3abbd9e7deac27263e1ee63c012e1114)), Ok(HeaderHash(0x8429248dacf0f30a5e09a948fba9e7165bb9c4ad55140f7198e1bd8537597dd0bc7c1cfd074c3b)), Ok(HeaderHash(0x8429248efc94a3110557904110fc0c2595cc7200d06caef3634a98a2d8558d55e3f4efff6fb3c0)), Ok(HeaderHash(0x842924c10697af4055a9ae4e0e797b1ccc3966cdd009d06cfcc4a3fa9aaef20756dc95d9fb5bf4))] })])
```
Which seems suspicious that 4 indexes are being removed (I would have expected only 2)

The relevant lines where `update_index` is called:
https://github.com/h-REA/hREA/blob/8109fac54f3055aa9608dc720ff87159db3c4263/zomes/rea_economic_resource/lib/src/lib.rs#L133-L137

**Comment by pospi** [comment]
Symptom of #319
