### ISSUE TITLE
define graphql resolvers for remaining 'read all' endpoints

### ISSUE THREAD

**Issue by Connoropolous** [holo-rea/holo-rea#320]
For each of the following, two things should be added:
1. the resolver
2. test code in `test` that exercises the endpoint

Since `economicResources` and `economicEvents` are done, they can be used as an example to base off of

e.g. `readAll` and `economicEvents` in this snippet:
https://github.com/h-REA/hREA/blob/81c2b0097d92cce4cd475e3e191a2d90fa30ee61/modules/vf-graphql-holochain/queries/economicEvent.ts#L20-L29

- [x] agents
- [x] organizations (wrap `agents` call and filter results)
- [x] people (wrap `agents` call and filter results)
- [x] proposals
- [x] satisfactions
- [x] fulfillments
- [x] intents
- [x] commitments
- [x] processes
- [x] units
- [x] processSpecifications
- [x] resourceSpecifications
- [x] agreements

**Comment by pospi** [comment]
Note that there's no need to test the cursors or pagination metadata for other endpoints as we're doing in `event_resource_list_api.js` since all endpoints are generated from the same macro. It's enough to simply verify that the outputs are returned in a list in the correct reverse insertion order.
