### ISSUE TITLE
throw 'unimplemented' errors for API queries that aren't and won't be implemented within MMR scope

### ISSUE THREAD

**Issue by Connoropolous** [holo-rea/holo-rea#323]
currently, when you graphql request for `Agent.relationships`, for example, you just get `null`. Preferable would be to get an error back, informing the developer the endpoint isn't implemented yet. Otherwise they won't know if they're just getting a normal null field or an unimplemented one.

## Query
This would all happen here: https://github.com/h-REA/hREA/tree/sprout/modules/vf-graphql-holochain/queries
- [x] requests
- [x] offers
- [x] agentRelationship
- [x] agentRelationships
- [x] agentRelationshipRole
- [x] agentRelationshipRoles

## Mutation
- [x] createAgentRelationship
- [x] updateAgentRelationship
- [x] deleteAgentRelationship
- [x] createAgentRelationshipRole
- [x] updateAgentRelationshipRole
- [x] deleteAgentRelationshipRole

## Resolvers
The rest would all happen here: https://github.com/h-REA/hREA/tree/sprout/modules/vf-graphql-holochain/resolvers

### Agent
- [x] Agent.relationships
- [x] Agent.relationshipsAsSubject
- [x] Agent.relationshipsAsObject
- [x] Agent.roles
- [x] Agent.commitments
- [x] Agent.intents
- [x] Agent.economicEvents
- [x] Agent.commitmentsInScope
- [x] Agent.economicEventsInScope
- [x] Agent.plans
- [x] Agent.processes
- [x] Agent.proposals
- [x] Agent.proposalsInScope
- [x] Agent.proposalsTo

### Agreement
- [x] unplannedEconomicEvents

### Commitment
- [x] stage
- [x] resourceInventoriedAs

### Fulfillment
Fine

### Intent
- [x] resourceInventoriedAs 

### Measure
Fine

### Economic Event
- [x] triggeredBy
- [x] triggers
- [x] previous
- [x] next
- [x] track
- [x] trace

### Economic Resource
- [x] economicEventsInOutFrom
- [x] economicEventsTo
- [x] previous
- [x] next
- [x] track
- [x] trace
- [x] commitments
- [x] intents

### Plan
- [x] involvedAgents

### Process
- [x] nextProcesses
- [x] previousProcesses
- [x] involvedAgents
- [x] unplannedInputs
- [x] unplannedOutputs
- [x] previous
- [x] next

### Process Specification
This file is missing completely, and should be added. The resolvers can remain unimplemented, but the following should exist:
- [x] commitmentsRequiringStage
- [x] resourcesCurrentlyAtStage
- [x] conformingProcesses

### Proposal
- [x] primaryIntents
- [x] reciprocalIntents

### Proposed Intent
Fine

### ProposedTo
Fine

### Resource Specification
- [x] defaultUnitOfResource (is tracked by issue #155)
- [x] commitments
- [x] intents
- [x] economicEvents

### Satisfaction
Fine (except that I am noting that the resolvers should be made conditional on VfModules enabled

**Comment by Connoropolous** [comment]
@pospi and @weswalla FYI I am beginning the effort to try to document which relational edges, of those that are enabled in DEFAULT_VF_MODULES, are actually implemented. Even if something is going to get done soon-ish, its still worthwhile to do this since it gets us all on the same page, and allows for any that do end up falling out of scope. 

I am using the Graphql Explorer + the modules/vf-graphql-holochain files to check.

**Comment by weswalla** [comment]
How would we do this? Define a custom gql error type and throw it in all the above resolver functions?

**Comment by Connoropolous** [comment]
I think it would just look like a regular javascript error, which is like

```js
throw new Error('error message goes here')
```

**Comment by Connoropolous** [comment]
@weswalla as soon as I can I'll continue my review of these, and post the rest. This for sure wasn't all of them. It was just quite a manual process to figure them out case by case
