### ISSUE TITLE
follow-ups to 'revision_meta'

### ISSUE THREAD

**Issue by Connoropolous** [holo-rea/holo-rea#343]
Still to do: needs some tests in `core-architecture` to assert that the data is returned and that it changes after an update. There may also be some work to do in the GraphQL layer but I'm pretty sure both `id` and `time` will be passed through without intervention. Possibly the `history` module needs to be enabled in the VF-GraphQL modules whitelist as well.

_Originally posted by @pospi in https://github.com/h-REA/hREA/issues/258#issuecomment-1192265852_

**Comment by pospi** [comment]
- [x] still needs to return the time field in a native JS date format

**Comment by pospi** [comment]
whoops, accidentally pushed the last of this straight to `sprout` so closing as completed by ce5a3f43 & c4828310
