### ISSUE TITLE
stringIdRegex for Unit symbols is not loose enough for something like `$`

### ISSUE THREAD

**Issue by Connoropolous** [holo-rea/holo-rea#354]
https://github.com/h-REA/hREA/blob/067ee13467a304140ca62deec084d7a4cfa7c6dc/modules/vf-graphql-holochain/connection.ts#L142

this regex doesn't pick up, and thus doesn't deserialize for zome calls, a Unit ID which is specified via an actual 'symbol' symbol, instead of a string. @pospi I am guessing this is not intentional

**Comment by pospi** [comment]
correct! That's an oversight. I guess a nongreedy match-all then?

**Comment by Connoropolous** [comment]
we could prevent matching digits, and that's it maybe
