### ISSUE TITLE
"Invalid outputs specifier" in Nix environment CI setup

### ISSUE THREAD

**Issue by pospi** [holo-rea/holo-rea#380]
Tracking https://github.com/NixOS/nix/issues/7624 which is preventing builds from completing. We'll likely also have to wait for Microsoft to roll out a fix to their Github release workflows infrastructure.

See https://github.com/h-REA/hREA/actions/runs/3953772815/jobs/6770406317

**Comment by pospi** [comment]
@Connoropolous FYI. If the pending update to Holochain `0.1.0` involves updates to the Nix environment then it may resolve this.

**Comment by Connoropolous** [comment]
@pospi some folks found a workaround so believe (but haven’t verified) 
![67996A70-02CD-4E62-A655-7ECE71485254](https://user-images.githubusercontent.com/1409121/215651300-19e168b1-2215-4f3c-8133-86a7c321abdb.png)

**Comment by Connoropolous** [comment]
https://github.com/holochain/holochain-client-rust/pull/11/files

**Comment by Connoropolous** [comment]
Specify nix as such in the GitHub actions file

**Comment by pospi** [comment]
Let's see, I'll put it in an unrelated PR I want to push through...

**Comment by pospi** [comment]
Looks to be working in https://github.com/h-REA/hREA/actions/runs/4050683106/jobs/6968305028, closing
