### ISSUE TITLE
Test process is too slow to execute on Github CI

### ISSUE THREAD

**Issue by pospi** [holo-rea/holo-rea#384]
I have an uneasy feeling that the CI process is substantially slower now. It does seem to be building holochain & hc from source, was it always doing that?
(prior to https://github.com/h-REA/hREA/commit/96dd149bd4a9b3d7fb8415010946ce713a0a0686)

**Comment by Connoropolous** [comment]
that's temporary, in a couple ways. Also though, we have `100 minutes` set ourselves in the Actions file so it could be increased, just FYI. Not that we want it to take that long or longer, and it doesn't have to. It will get better again, when the nix issue gets fixed and we can remove the special nix settings, and also when it has run and been cached in cachix, which it now has

**Comment by Connoropolous** [comment]
Nix stage is only taking 2 minutes after updates
