### ISSUE TITLE
ERROR: [HOLOCHAIN 0.0.162] kitsune_p2p_types::tx2::framed: writer closing due to error e=KitsuneError(TimedOut("FramedWriter::write"))

### ISSUE THREAD

**Issue by amunrarara** [holo-rea/holo-rea#392]
Cheers,

I'm attempting to install hREA-graph-ql-explorer into Holochain Launcher as per the instructions here: https://docs.hrea.io/quick-start

I have downloaded hrea.webapp from the linked build (happ-0.1.2-beta), and begun the installation from the file. After selecting the file (Select app from filesystem), Launcher is stalling with "Processing file...". 

In my logs, this is the error that keeps repeating itself: 

```

[2023-03-18T18:41:52.920850+02:00] INFO - [HOLOCHAIN 0.0.162] [2mMar 18 18:41:52.919[0m [33m WARN[0m kitsune_p2p_types::tx2::tx2_pool_promote: Closing writer e=KitsuneError(Closed)

```

I was not given an option to choose the Holochain version specified; perhaps that is the issue? Should I be using a custom Holochain binary, instead, from the configuration menu?

**Comment by pospi** [comment]
It could be, but Launcher authors would know better about that. If so I'd see this as an upstream bug- I would have expected hApps built to different patch-versions of the HDK to still be compatible (ie. a `0.1.3` conductor should be able to execute `0.1.0` zome binaries).

@guillemcordoba @Connoropolous @maackle if any of you are able to shed light on expectations regarding zome WASM compatibility and HDK/HDI versions?

**Comment by maackle** [comment]
I'm not sure, but that error may be a red herring. It might also be good to check with the hREA folks to see which conductor version they're targeting. Also I notice you're using holochian `0.0.162`, which is alpha and doesn't have the same compatibility guarantees as 0.1.x, so you may want to update your launcher which will give you a 0.1 conductor to work with.

**Comment by adaburrows** [comment]
I do know that Launcher v0.9.0 - v0.9.4 comes with Holochain v0.1.3. So it seems very odd that you would have Holochain v0.0.162.

@amunrarara Can you confirm that you are using the Launcher v0.9.0 as indicated in the instructions?

**Comment by adaburrows** [comment]
Based on the version of Holochain you seem to be running, I'm going to guess you're actually running the Launcher v0.7.0 (this one is broken and has been deleted off Github, FYI) or v0.7.1. Both of which are not capable of running the latest hREA release.

<img width="552" alt="Screenshot 2023-04-07 at 13 25 13" src="https://user-images.githubusercontent.com/102320/230674311-53d224e7-6477-4a92-b87d-7e2c9b2ddb31.png">

<img width="289" alt="Screenshot 2023-04-07 at 13 24 18" src="https://user-images.githubusercontent.com/102320/230674218-449bb545-47af-4856-8dbe-8b55f7590ccd.png">

**Comment by pospi** [comment]
@amunrarara see how you go with [Launcher v0.9.4](https://github.com/holochain/launcher/releases/tag/v0.9.4) on the latest release, which we just recompiled for Holochain 0.1.3- https://github.com/h-REA/hREA/releases/tag/happ-0.1.3-beta

If you have any problems, please reopen this issue. :crossed_fingers: for now that this will work without issue!
