### ISSUE TITLE
Import to Holochain Launcher

### ISSUE THREAD

**Issue by entin-hun** [holo-rea/holo-rea#404]
How to install it properly?
Following [your guide](https://docs.hrea.io/quick-start#install-hrea-graphql-explorer), I downloaded [latest .webhapp file](https://github.com/h-REA/hREA/releases/download/happ-0.1.3-beta/hrea.webhapp), but when imported to Launcher 0.400.0-alpha.10 ([the link to 0.9 is broken in guide](https://github.com/holochain/launcher/releases/tag/v0.9.0)), this error message appears:
`WasmError { file: \"/Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/holochain-0.4.0-dev.12/src/core/ribosome/real_ribosome.rs\", line: 404, error: Compile(\"Error while importing \\\"env\\\".\\\"__hc__remote_signal_1\\\": unknown import. Expected Function(FunctionType { params: [I32, I32], results: [I64] })\") })`

How to properly install the UI? Should prepare via CLI as `cargo install holochain --version 0.1.3 --locked` ?

**Comment by LeosPrograms** [comment]
Hi Entin, you need an older version of the Holochain Launcher for that .webhapp file. Try this: https://github.com/holochain/launcher-tauri/releases/tag/v0.11.5

Feel free to reach out further if you need any help using hREA.

**Comment by entin-hun** [comment]
Thank you, now it works!
