### ISSUE TITLE
Finalise fulfillment & satisfaction data structures

### ISSUE THREAD

**Issue by pospi** [holo-rea/holo-rea#42]
These need to provide for the intermediary records (they currently link directly between `EconomicEvent`, `Commitment` and `Intent`) and all CRUD methods as deemed appropriate by https://github.com/holo-rea/holo-rea/issues/37.

Once finalised we can roll this pattern out to all zome API handlers and complete the Observation and Planning modules.

**Comment by fosterlynn** [comment]
Made some changes to those records in the current VF release, fyi.  Should be stable for now from that side.

**Comment by pospi** [comment]
@fosterlynn I'm going to have to set this up so that fulfillments can only be managed via the planning DNA for now... does that sound like the most sensible course of action?

Can't have it work both ways- see https://forum.holochain.org/t/bidirectional-bridging/705

**Comment by pospi** [comment]
I've actually done it the other way around, which I think makes more sense. A participant has no reason to log fulfillments if not for commitments they are aware of, correct? So should it not be something that is done in the planning DNA?

I think I see it as "fulfilling a commitment" is an action which happens in the `planning` module, and `observation` modules are notified (retroactively) by planning modules that their events have gone to fulfill other commitments. 

To be clear- the records end up on both sides. [See complete test case](https://github.com/holo-rea/holo-rea/blob/d1cb52a/test/core-architecture/test_links_cross_dna.js#L13) to get a sense of the data and links involved.

**Comment by pospi** [comment]
I think it should be bidirectional, ideally- participants with access to either network should be able to trigger saving the fulfillment. But we'll see what the core team says about cyclic dependencies in DNA bridging configurations.

**Comment by fosterlynn** [comment]
>I think it should be bidirectional, ideally- participants with access to either network should be able to trigger saving the fulfillment.

What is the use case you imagine for coming at it from the commitment side instead of when logging an event?  And what is the use case when would someone saving a fulfillment not have access to both observation and planning?

**Comment by pospi** [comment]
I think I'll split this out and log as a separate issue when it becomes an important detail. For now it's a minor technical thing- someone saving a fulfillment should always have access to both DNAs; the concern is only for others reading.

The basic implementation is more or less complete now, I just need to loosen the validation on the `Satisfaction satisfiedBy Commitment` links, since they are optional (can also reference an `EconomicEvent` in a foreign DNA). Expect a PR tomorrow some time.

**Comment by fosterlynn** [comment]
>I just need to loosen the validation on the Satisfaction satisfiedBy Commitment links, since they are optional (can also reference an EconomicEvent

That's probably one I forgot earlier, one of those has to be present (Commitment or EE).

**Comment by pospi** [comment]
Completed in #59.
