### ISSUE TITLE
What is HoloREA?

### ISSUE THREAD

**Issue by sqykly** [holo-rea/holo-rea#5]
It's a "modular" VF implementation on Holochain, yes.  But the architecture of the program depends strongly on the exact protocol through which a client app interfaces with a "module".  We need to decide what "module" really means to us.  This issue can serve to collect our thoughts and knowledge in advance of the next meeting, and to hold our conclusions afterward.

## Drop-in zomes

A drop-in zome is source code that Holochain developers can include in their own projects.  The interface with our code would be cross-zome methods, which have a special declaration in the DNA and a special way they must be called:

    let vf_data = call("name_of_holorea_zome", "name_of_holorea_function", argument);

The VF model objects would live on the same DHT as the rest of their app. Any object created by the zome(s) is validated in our own zome.  After that, our data is at the mercy of the host app's security strategy, i.e. there is no point in building in access control.  The host app ultimately has total control and our zome(s) operate with full transparency to it.  It would be trivial for developer to break our zome in some way, but that transparency also creates possibilities that may be impossible otherwise by allowing the host app to use or redefine our types.

If desired _by the host app_, the special DNA declaration can also expose our functions as web API or bridge functions.  We can't guarantee any part of an API we define will be a part of an app running HoloREA.  We also have no configuration data apart from what we require from the host app to run.  We can effectively never push an update,

## Bridged apps

Like drop-in zomes, only Holochain developers can use a bridged app.  Our DNA will define a set of bridge functions, which may be called from the client app.  Instead of `call`, there is a similar HDK function:

    let vf_object = bridge("name_of_holorea_app", "name_of_zome", "name_of_function", argument);

Our data lives on a different DHT than the client app.  We do all of our own validation and access control.  We control the configuration data and our own DNA, so we decide which parts of the API we expose at every level.

I _don't think_ we will have a different DHT for each client app by default; we will need to juggle multiple data sets for different apps.  I _think_ we can use configurations to make each client app's HoloREA a different app hash, which would relieve this problem where the client app plays along.  Whether this will affect updates to HoloREA, I don't know.

## Web API

This is how it worked in the prototype.  Every hApp runs a server that serves requests for static content and requests to the web API endpoints its DNA declares.  The client app can then be anything, not just another hApp.  A web browser can access our default UI (like the REPL), or another app can use our API and serve its own pages (like our separate UI server).  Client apps call our functions via requests:

    POST holorea-server/fn/holorea-function-name

A web API can also be used as a bridged app if we declare so in our DNA.  It _could_ be used as drop-in zomes, but doing so will cede the advantages of being an independent app.  It would also make security very difficult.  Let's not do that.  Bridging might be okay.

In most other characteristics, this situation is identical to a bridged app.  The difference is only in how the API functions are declared in the DNA.

-----------------------------

Questions, comments, additional facts before I weigh in?

**Comment by pospi** [comment]
First thoughts in response:

- I don't think the architecture of our work depends all that much on the protocol through which a client app interfaces with the VF protocol. Whether the boundary ends up being 'zome' or 'DNA', most of our code will be identical. The only difference is likely to be in validation, which will be a different API call if modules are within the same DNA as separate zomes; or multiple DNAs connected via bridging (in this latter case, validation being potentially impossible). Also, in the case of modules being delivered as DNAs there will be some extra logic around them, but the core will still be the same zome code as it would have been were it released as an independent package.
- *'Web API'* isn't a type of modularisation- it's part of the "conductor" layer and is determined by how the conductor exposes the DNA functions to the outside world. We *may* decide on a *'GraphQL gateway'* architecture that proxies requests from an entrypoint zome that services the GraphQL queries into other backend zomes; however that being the case, the modules themselves are still composed of either zomes or DNAs.

> It would be trivial for developer to break our zome in some way

I disagree with this. If we implement our core logic in a way that takes advantage of the Rust type system it should be largely impossible for calling code to 'break' our zome without hacking at its code.

> We can't guarantee any part of an API we define will be a part of an app running HoloREA

I don't see how that fact changes in either case. Regardless of what we do, other developers have the power to do things differently. The only useful guarantees about whether an app services ValueFlows data come from the external GraphQL validation tooling.

> We also have no configuration data apart from what we require from the host app to run

I'm sure there will be some process, even if just by documentation conventions, to indicate what DNA configuration variables are necessary for integrating a zome. Our code should probably panic if any configuration variables it depends upon aren't declared.

> We can effectively never push an update

I don't think we want to make ourselves responsible for updates. A hApp implementing ValueFlows should include our module within it and manage all updates to it alongside updates for other modules relevant to its community of interest.

> We do all of our own validation and access control

Need to figure out how to manage this validation ourselves, as HDK devs have indicated it's not possible. But possibly if both zomes have access to our validation logic we can load up the record from the other DHT and check it's valid. I would imagine almost all our cross-module validation is just of the "does this record exist?" type, though.

> I don't *think* we will have a different DHT for each client app by default

Not sure I understand this. *"use configurations to make each client app's HoloREA a different app hash"* means making every client app a different DHT, doesn't it? Also factors in to my above comment on "never push an update".

> *could* be used as drop-in zomes, but doing so will cede the advantages of being an independent app

Still not sure what the advantages / disadvantages between the two approaches are, unless related to what I've expressed above (:

**Comment by pospi** [comment]
Notetaking from conversation with @artbrock:

- The DNA / zome decision is more about unity (same network, calls between) than architecture.
- If you're mixing the same zome into a lot of different business use-cases; none of those businesses are talking on the same network. There's an opportunity for HoloREA to become a new "value network" (so you still may have many different HoloREA networks), but what you want to do is use HoloREA as a transport for "binding the duality" of valueflows and constructing business rules as separate networks. So basically using it as a bridge between businesses with different business rules.
- Example: a medical marketplace that records the acts of data having been shared between parties (by direct message sending), but not the data itself. Then a private DHT which holds personal medical info where the data is actually stored.
- So it's about having a 'shared' network space as a communication overlay *between* 'local' networks.
    - Note that if using message sending to transmit data, both parties need to be online simultaneously
- Art can see the need for a similar role in ValueFlows. You want to be able to bind to events, propagate publicly visible trades out to the wider network etc. Even if it's not the heart of the inventories, ontologies etc this kind of service probably needs to be one of the modules in HoloREA.
- How much data do we expose to the "shared" network?
- Knowing where to draw the membrane is the difficult question.
- One marketplace per vertical may be one way of doing it.
- We may have to make choices about what kinds of use-cases we want to favour, and create spaces to facilitate that (eg. 'open' vs 'proprietary' logics).
- **Possible architecture:** 'shared' network space contains the economic ledger (events & resources). Likely separate network spaces delineated by the ontologies connected to the resources & events; since those form up the available concepts in the communication space. Possibly one 'shared' network per market vertical.
- Having an easy way to import existing ontologies is highly necessary.
- Use-case to think about: supply chain planning & coordination.
    - Car producers simply send parts requests to suppliers based on how many cars they want to build.
    - Suppliers are then responsible for bringing parts to the production line as needed.
    - Suppliers paid when cars come off the line, because without the parts the cars couldn't have been built.
    - So an independent network view & internal trading partner view.
        - Network sees 'from' & 'to' agent; transactions are mirrored internally for each of the trading partners. *Network has a view of the whole thing.*
    - Some agents in the supply chain may want to use different apps alongside their HoloREA module.
    - May also want to connect to marketplaces to trade what's being produced in the supply chain.
    - Thoughts:
        - In order to be able to communicate on HC, you need to be sharing a DNA.
        - You can only mutually enforce rules between a shared DNA.
        - You *can* bridge between DNAs, but no rule enforcement can be done between them.
- We may need to implement separate schemas for 'external' & 'internal' views; though only needed if there's an advantage in doing this.
- **Capability tokens** provide one unified security model for HC:
    - Access requests are signed by the requesting address
    - Capabilities are awarded in response to call particular functions
    - When another app is running locally, we can register a capability token that functions as an API bridge
    - To expose private info, can create capability tokens to allow reading of a particular single entry from private source chain. Private entry can be retrieved whenever the caller wants now (if the agent being read from is online).
    - This likely solves a lot of the group agent decisions we need to make.
- **Group agents:**
    - Option: Someone runs an agent instance on behalf of the group.
        - Create an agent representing a group and provide capability to individuals to call actions on its behalf
        - Actions are logged as "individual has taken an action"; but "acting on behalf of the group" *(both bits of data are present)*
    - Alternative: write an abstraction into your app to manage groups
        - No physical centralisation of the group in this design
        - One cannot call DHT functions *as if the group had called them itself*. ie. calling code needs to be aware of this abstraction; delegating agency in this way is counter to the design philosophy of Holochain.
        - Everything which needs to be aware of this abstraction needs to be aware of it (agents would have to pass group entry hash in addition to other params)
        - Holochain will probably (in future) write such an abstraction so there is some well-formed version of it
        - The best (most neatly contained) place to manage such an abstraction is probably in the validation rules
        - If we have an abstraction for `vf:Agent` anyway, the group abstraction is not so different anyway.
    - Alternative: have a group agent composed of a DNA
        - (as per medical network example above)
        - Marketplace bridges to a DNA, not just an endpoint
        - Similar constraints to in-app abstraction (agents would have to pass DNA hash in addition to other params)
- *'Progenitor'* nodes:
    - Any node booting up hasn't connected to anyone yet so as far as it's aware it's the only one in the universe.
    - So you hardcode a particular key into the DNA as the agent who is spawning the network.
    - No ongoing status or anything, it's just an agent like any other and can remove itself from any DHT state describing privileged access after bootstrapping. So this is the "person who starts the group", type thing.
- Agent abstraction:
    - Aside from groups, we have two needs: metadata & query entrypoints.
    - Metadata: can be attached directly to your agent by linking
    - Query entrypoints: could be implemented through the other DHTs (observation, planning etc) reasonably easily
    - Guideline: learn how to use a Holochain agent before implementing more abstraction to make sure we aren't just reimplementing stuff
    - You *could* use the same key in multiple apps, but you can/should use different ones, too.
    - **Likely outcome:** we don't need an REA-specific agent abstraction.

**Comment by bhaugen** [comment]
One very minor correction, but it tells something about the data sharing in the supply chain:
> Car producers simply send parts requests to suppliers based on how many cars they want to build.

The car producer previously shared the whole bill of material structure with their supply chain, so each supplier knew which of their components was required to build a car. So the auto producer did not need to send parts request, they just needed to send the final assembly schedule and the suppliers were supposed to figure it out from there. Which of course they knew how to do or they would not stay in the auto component supplier business very long. 

I'm not sure if each car producer did it all exactly that way. I know some of them depended on their tier one suppliers to coordinate the lower tiers of the chain. But the data each supplier needed got shared one way or another and parts requests were becoming obsolete in some chains even in the 1990's.

**Comment by sqykly** [comment]
I believe that given the constraints and direction we all heard, the bridged app model is the only one that meets our needs.

- HoloREA needs a central DHT; drop-in zomes would create a separate space for each host app.
- The web API can't be used for remote access without discarding and duplicating the HoloREA authentication functionality.

Data exposure management across this monolithic DHT is then the problem.  Art gave several suggestions, which I'll make a new issue for.

@pospi @bhaugen @ivanminutillo @fosterlynn does everyone concur with this conclusion?

**Comment by fosterlynn** [comment]
>HoloREA needs a central DHT
>does everyone concur with this conclusion?

I am speaking from a position of extreme ignorance of the guts of HC, so I probably didn't understand some of the implications from Art, just making that clear (I know it was already :blush: ).  But I can't see how we can do this with a central DHT for HoloREA, honestly.  Besides the privacy implications, that's a *lot* of economic activity if this takes hold.  I'm posting because you asked the question.  I'll wait and see what the whole architecture looks like and try to form an informed opinion.  Pictures would be great as soon as they start to form in anyone's mind.

**Comment by sqykly** [comment]
Sorry, I misunderstood what Art was saying.  There are any number of DHTs, each representing one network.  

- Agents can be members of any number of networks using the same agent credentials in each.
- Every agent on a network has access to all data on that network.
  - There is little to no need for local chain storage and selective sharing as I described in #7
- Networks can be connected through a network-bridging zome
  - Cross-network references are Holo-URIs, whatever that turns out to mean.  It's logically equivalent to the placeholders I described for #7 
    - This means _all_ of our references need to be Holo-URIs?
  - Access control for network-public data is realized through capability tokens issued when networks are bridged
- All ontology data is an opaque URI.  Some mechanism is provided to manage equivalences between networks that use different ontologies.

**Comment by pospi** [comment]
Correction: agents can use the same *or different* credentials on each network.

> This means all of our references need to be Holo-URIs?

I think so too. Seems sensible to aim for consistency.

> Some mechanism is provided to manage equivalences between networks that use different ontologies.

This will likely take the form of additional marketplace networks which connect resources from bridged networks by defining ontological equivalences between them.

Yes, all agreed!

**Comment by fosterlynn** [comment]
>All ontology data is an opaque URI. Some mechanism is provided to manage equivalences between networks that use different ontologies.

@sqykly I want to make sure I understand what you mean.... is this like type / classification / taxonomy data?

**Comment by sqykly** [comment]
@fosterlynn yes

**Comment by pospi** [comment]
Just doing a cleanup... If this issue has been satisfactorily answered, please close!

**Comment by sqykly** [comment]
Yep, this one's good.
