### ISSUE TITLE
Implement EconomicResource

### ISSUE THREAD

**Issue by pospi** [holo-rea/holo-rea#53]
These need to be stubbed out and wired up to `EconomicEvent` API handlers. Note that VF 0.3 defines some fields as "may be calculated"- I think the appropriate behaviour there is to use a value where present and derive the field if an explicit value has not been set. Does that sound correct @fosterlynn?

**Comment by fosterlynn** [comment]
Would it be easier to always assume a value will be present?  And make sure in our economic event mutations that those quantities in fact always are present and up to date?  I think we will quickly get to where recalculating on the fly will not be performant in many cases, so might as well just do it all the same way.

**Comment by pospi** [comment]
I don't think it will add too much undue complexity if it operates as I outlined- it will just be one or two extra statements per field. I say we do it properly first pass!

**Comment by pospi** [comment]
First pass completed in #66.
