### ISSUE TITLE
Implement zome validation callbacks

### ISSUE THREAD

**Issue by fosterlynn** [holo-rea/holo-rea#56]
See https://github.com/valueflows/vf-apps/issues/5.

For either / or fields, there are some fields where one or the other is required.  These are:
* Intent, Commitment, EconomicEvent, RecipeFlow, Claim, Process: at least one of the time fields
* Intent, Commitment, EconomicEvent, RecipeFlow, Claim, Fulfillment, Satisfaction, Settlement: resourceQuantity or effortQuantity (or both)
* Intent, Commitment, EconomicEvent: resourceClassifiedAs, resourceConformsTo, or resourceInventoriedAs (mroe than one is fine)

**Comment by pospi** [comment]
See https://github.com/willemolding/generic-game-holochain/blob/d9abc62/zomes/main/code/src/game.rs#L144 for an example to follow.

**Comment by pospi** [comment]
Done and ready for merge, will review with EYSS team tomorrow
