### ISSUE TITLE
Sign off on contributor guidelines

### ISSUE THREAD

**Issue by pospi** [holo-rea/holo-rea#58]
I just wanted to draw this out into an explicit decision- I've added a section on [contribution agreements](https://github.com/holo-rea/holo-rea/blob/8198238/CONTRIBUTORS.md#contributor-workflow--coordination-protocol) to the contributors doc in the repo in response to more interested third-parties and potential contributors reaching out.

Since you two are the other major stakeholders in this at the moment I wanted to run it by your eyes and ask for any input; at least one other person should OK this before we start living by it. Feel free to provide suggestions & comments here, or as PRs.

**Comment by fosterlynn** [comment]
Looks OK to me.

**Comment by pospi** [comment]
Closing this- @JhonatanHern is up and running
