### ISSUE TITLE
Agent-centric architecture

### ISSUE THREAD

**Issue by fosterlynn** [holo-rea/holo-rea#6]
I haven't dug into much of the technical architecture of Holochain, so if you @sqykly and @pospi tell me this is dumb, I'll close it.  But I have wondered this for quite a while.

Holochain is "agent-centric", we all want to be "agent-centric" too.  But how does it work?  (I've thought about it quite a bit in our ActivityPub track, so I'll use that to translate over to here.)

Some different aspects of my questions:
1. Can we make something agent-centric out of what I understand Holochain provides, which is more like user key centric?  If not, 
2. Where are we with the extended discussion about group agents that @bhaugen and Paul D were having earlier?   (I won't repeat it here, but can pull some things into github later if useful.)  Basically, we see the need for group agents to also be part of the agent-centric paradigm.  Not so much in terms of having a user key, but in terms of having their own source chain and whatever else is needed for owning their own data.  And person agents could have role-based permissions to act on behalf of the group agent based on the group's governance.
3. How should we think of group agent-ness related, in relation say to hApps and DHTs and such?  I picture group agents having their own choice of apps that they use, which would first save their data in the group's source chain, and then...?  Interaction from person agents who are part of the group could be carried out from a UI based on the person's home base.  But the software would need to be coordinated with the group's software.  The group's software would have most of the backend logic.  Where does that live in the hApp / DHT / DNA architecture of holochain?

Apologies again for not being very deep into the architecture, for any wrong terms I used, etc.

**Comment by pospi** [comment]
> Can we make something agent-centric out of what I understand Holochain provides

Yeah. Agent hashes have the same format as entry hashes, so we can use raw Holochain agents at first and then migrate over to more complex records that wrap up other data into the "agent" concept if needed.

> Where are we with the extended discussion about group agents

Nowhere much further. [See here for latest update](https://github.com/holo-rea/ecosystem/wiki/Coordinating-the-REA-community-of-practise#group-agent). I know @thedavidmeister had some thoughts on how to simplify implementing this with "verifiable claims".

> How should we think of group agent-ness related?

I'm not really sure. Ideally there is a way that we can have group agents call methods in other DHTs as if they are for all intents and purposes singular agents; such that the apps to be managed by individual or group agents don't have to think about what type of agent is manipulating them. But I'm unsure if such an architecture is possible.

One requirement is that the IDs (hashes) for individuals, entries and DHTs are all equivalent (which they are). This means a group agent defined as an entry record, or a group entry defined as a separate app DNA, can both be assigned in place of a "normal" agent as owner of things.

The other requirement is that the group agent can "act" by executing methods elsewhere in the system, if its internal logic for determining consensus allows a member agent to call a method on its behalf. This is the feature I'm not convinced exists; and unsure what the alternative might be (if there is one).

**Comment by pospi** [comment]
Some good information on this came out of a recent conversation with @artbrock https://github.com/holo-rea/holo-rea/issues/5#issuecomment-484300020

**Comment by sqykly** [comment]
> I'm not really sure. Ideally there is a way that we can have group agents call methods in other DHTs as if they are for all intents and purposes singular agents; such that the apps to be managed by individual or group agents don't have to think about what type of agent is manipulating them. But I'm unsure if such an architecture is possible.

I don't understand what you mean by "call methods in other DHTs".  Do you mean in other DNAs?  Other zomes?  On other nodes?

> One requirement is that the IDs (hashes) for individuals, entries and DHTs are all equivalent (which they are). This means a group agent defined as an entry record, or a group entry defined as a separate app DNA, can both be assigned in place of a "normal" agent as owner of things.

But do we want that to be the case?  Does it make sense to have an app be the `receiver` of an `EconomicEvent`?  Do we have `AgentRelationship`s with an `Action` entry?  I don't know if there is any way to assert sensibility in this regard in validation.  I really don't think there's a way to validate without an entry type.  For "DHT hash" do you mean app hash or agent hash?

> The other requirement is that the group agent can "act" by executing methods elsewhere in the system, if its internal logic for determining consensus allows a member agent to call a method on its behalf. This is the feature I'm not convinced exists; and unsure what the alternative might be (if there is one).

We'll know more about this once there is decent documentation on Holochain's Capabilities implementation.  The way I heard it last night, they should allow a function call.  But whether or not this fits the bill for this purpose depends on what a group agent _is_.

This is a good start for the specific requirements of a group agent, let's keep it up:

An agent of any kind must be able to sign things and conduct data transfers peer-to-peer.

**Comment by pospi** [comment]
Closing this as #9 deals with the specifics of implementing required compatibility logic for group agents.
