### ISSUE TITLE
Restructure zome modules as appropriate for third-party integration

### ISSUE THREAD

**Issue by pospi** [holo-rea/holo-rea#80]
There's a bunch of naming conventions to align on and standardise first, see https://forum.holochain.org/t/naming-conventions-module-patterns-for-rust-crates/1294/2

Then it will be a case of changing the names of the zome crates & wiring up dependencies; and shuffling API handler function names around to make them saner for importing, probably looking at standardised sub-module names. The module structure implemented in those modules already converted can be used as a pattern to follow.

- [ ] observation DNA
    - [x] economic event
    - [x] economic resource
    - [x] process
    - [ ] fulfillment
    - [ ] satisfaction
- [ ] planning DNA
    - [ ] commitment
    - [ ] intent
    - [ ] fulfillment
    - [ ] satisfaction
- [ ] specification DNA
    - [ ] process specification
    - [ ] resource specification
    - [ ] unit
- [ ] proposal DNA
    - [ ] proposal
    - [ ] proposedTo
    - [ ] proposedIntent

---------------

*(note: these items are worth splitting out to their own issues):* 

Step 2 involves the `identifiers` constants present in each module. Many `_defs` and `_storage` crates depend on common entry & link type identifiers that are shared in foreign key entries split between DNAs. Resolving this unnecessary coupling involves splitting **remote key index** entry & link type definitions out into separate zomes for better compartmentalisation, which is mainly a case of changing `to!` links to `from!` ones. (eg. `Process` record address stubs are defined in the `commitment` zome but they also link to the `intent` zome, so should be in their own separate `process` zome).

We also need to address how to make this more "mixin-y", probably by genericising this `process` zome into a `links` or `anchors` zome that can be generically called from both `commitment` and `intent`. Otherwise it's non-trivial to configure a generic `process` link registration zome to link to both `Commitment` and `Intent` entry types...

Remember to create documentation for implementors in the ecosystem wiki and iterate it as we go.

The rest is probably a dance with implementors to see what subsets of functionality they need to include in their projects, and how we can make integrating those features as little effort as possible. "Entire zome" and "just datatypes and API handler interface" is certainly necessary, and a good place to start.

**Comment by fosterlynn** [comment]
>probably by genericising this process zome into a links or anchors zome that can be generically called from both commitment and intent

also needed for observation layer for people doing production/creation without planning

**Comment by sidsthalekar** [comment]
> create any additional helper libraries for use in third-party zomes which wrap up the management of entries and links defined in our mixin zomes in order to make interfacing with them easier

> create documentation for implementors in the ecosystem wiki and iterate it as we go

This would be very helpful. Eager to participate in this process.

**Comment by pospi** [comment]
Something I am noticing is that [the entry & link type IDs](https://github.com/holo-rea/holo-rea/blob/d5776ac456ffea5afd2dfd40281eb584baa0a098/lib/rea_process/structs_internal/src/lib.rs#L92) are referenced by zome defs & `_structs_internal` of *other* zomes, which makes that import quite weighty just to share constants. There's also an argument to be made that internal entry / link type defs *shouldn't* be shareable between zomes, but I haven't followed through my lingering dependencies to find out whether or not that's the case yet. (I suspect it might be, when looking at the defs in eg. [EconomicEvent](https://github.com/holo-rea/holo-rea/blob/d5776ac456ffea5afd2dfd40281eb584baa0a098/lib/rea_economic_event/defs/src/lib.rs#L12) and noticing those `to!` links could just as easily be `from!` links in a separate zome module.)

**Comment by pospi** [comment]
Completed in #121
