### ISSUE TITLE
Implement correct logic for `EconomicResource.conformsTo`

### ISSUE THREAD

**Issue by pospi** [holo-rea/holo-rea#96]
Overflow from #56; needs to be pulled out into a separate issue as the logic is unclear. The most agreeable logic for setting the `EconomicResource.conformsTo` field during an `EconomicEvent` creation so far seems to be:

- `EconomicResourceCreateParams.conformsTo` should no longer be required in the GraphQL schema.
- if `EconomicResourceCreateParams.conformsTo` is provided, use this value as a first priority.
- failing that, use `EconomicEvent.resourceConformsTo` if provided.
- if neither of the above fields are present, the resource / event creation operation is an error.

Does this sound like what we want to go ahead with?

**Comment by fosterlynn** [comment]
>f neither of the above fields are present, the resource / event creation operation is an error.

This seems incorrect - if we aren't requiring the field, then it shouldn't be an error.

**Comment by pospi** [comment]
I thought we were going to stay with requiring it... I'm hesitant to allow people to create resources which have absolutely no ontological bindings. If we're making `conformsTo` not required, can we at least say that `EconomicResource` must have either `conformsTo` or at least one `classifiedAs`?

If we were to take this approach, it would mean revising the above as:

- if `EconomicResourceCreateParams.conformsTo` is provided, use this value as a first priority.
- failing that, use `EconomicEvent.resourceConformsTo` if provided.
- failing *that*, there can still be an error but only if `EconomicEvent.resourceClassifiedAs` is not provided.

**Comment by fosterlynn** [comment]
Trying to make it as simple as possible for people who might want that.  But do whatever you prefer, let's just get it out there and we'll see.
